language: python
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - gem install bundler
  - make install
script:
  #- make runall
  - make book
after_success:
  - make build
deploy:
  provider: pages
  local_dir: _site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: jupyter-book
