language: python
python: "3.7"
install:
  - pip install -r requirements.txt
script:
  - bash gen-html.sh
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master