language: python
python: "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - gem install bundler
  - make install
script:
  - make runall
before_deploy:
  - make book
  - make build
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
